version: '3'
services:  
  web:    
    build: .    
    ports:      
      - "80:80"   
    volumes:      
      - ./nginx.conf:/etc/nginx/conf.d/default.conf      
      - ./:/usr/share/nginx/html    
    restart: always  

  ngrok:    
    image: ngrok/ngrok:latest   
    ports:      
      - "4040:4040"    
    environment:      
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}    
    command: http web:80    
    depends_on:     
      - web
